version: '2'
services:

  www_balancer:
    container_name: www-balancer
    restart: always
    build:
      context: ${HOME}/fibonacci/nginx
    ports:
      - 80:80
    volumes:
      - ${HOME}/fibonacci/logs/balancer/:/var/log/nginx
    links:
      - www_fibonacci

  php_fibonacci:
    container_name: php-fibonacci
    restart: always
    build:
      context: ${HOME}/fibonacci/php-fpm/fibonacci
    volumes:
      - ${HOME}/fibonacci/logs/var/fibonacci:/var/log/
      - ${HOME}/fibonacci/www/fibonacci:/var/www/fibonacci

  www_fibonacci:
    container_name: www-fibonacci
    build: ${HOME}/fibonacci/nginx/fibonacci
    volumes:
      - ${HOME}/fibonacci/logs/nginx/fibonacci:/var/log/nginx
      - ${HOME}/fibonacci/www/fibonacci:/var/www/fibonacci
    restart: always
    links:
      - php_fibonacci
